AWL_MODEL: # element recognition model -- logo only
  CFG_PATH: configs/faster_rcnn_web.yaml
  WEIGHTS_PATH: models/layout_detector.pth
  DETECT_THRE: 0.3

CRP_CLASSIFIER:
  WEIGHTS_PATH: models/crp_classifier.pth.tar
  MODEL_TYPE: 'mixed'

CRP_LOCATOR: # element recognition model -- logo only
  CFG_PATH: configs/faster_rcnn_login_lr0.001_finetune.yaml
  WEIGHTS_PATH: models/crp_locator.pth
  DETECT_THRE: 0.05

SIAMESE_MODEL:
  NUM_CLASSES: 277 # number of brands, users don't need to modify this even the targetlist is expanded
  WEIGHTS_PATH: models/ocr_siamese.pth.tar
  OCR_WEIGHTS_PATH: models/ocr_pretrained.pth.tar
  TARGETLIST_PATH: models/expand_targetlist.zip
  MATCH_THRE: 0.87 # FIXME: threshold is 0.87 in phish-discovery?
  DOMAIN_MAP_PATH: models/domain_map.pkl